### ISSUE TITLE
trang not found in make process

### ISSUE THREAD

**Issue by kohlhase** [slatex/LaTeXML-Plugin-sTeX#110]
On Mac OS I get 

```
Entering /mounted/lmh/ext/LaTeXMLsTeX
Running Makefile.PL
Configuring /mounted/lmh/ext/LaTeXMLsTeX ... Can't exec "type": No such file or directory at Makefile.PL line 14.

Trang is not found which could lead to a make failure.
You can ignore this message if you do not intend to change the schema.
See README for more info!

make: trang: Command not found
make: *** [LaTeXML.rng] Error 127
Generating a Unix-style Makefile
Writing Makefile for LaTeXML::Plugin::sTeX
Writing MYMETA.yml and MYMETA.json
```

but `trang` is installed in `/usr/local/bin/trang`.

**Comment by angerhang** [comment]
The message you got comes from `type` which does not exist in the Debian distribution that we are using for `lmh_docker` so I added `which` to the checking as well. `which` does exist in Debian.

I think what we should really is to provide `trang` inside the docker image by default (see https://github.com/KWARC/localmh_docker/pull/29) because this checking mechanism won't have the access to the resources outside the docker. (this is the nature of having a docker) Even if the checking works, it would still don't know if we have `trang` installed on the host system or not.

The checking here is mainly for the developers using the plugin outside the docker so that they are informed about the need of `trang` if they would like to customize the scheme, and the detection mechanism does work outside docker now (being tested on both Mac and Ubuntu)

**Comment by kohlhase** [comment]
seems to be a duplicate of #116
